# Override per sviluppo con hot reloading ottimizzato

services:
  backend:
    volumes:
      - ./backend:/rails
      - bundle_cache:/usr/local/bundle
      - /rails/tmp
      - /rails/log
    environment:
      - RAILS_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
      - BOOTSNAP_CACHE_DIR=/rails/tmp/cache/bootsnap
    stdin_open: true
    tty: true

  frontend:
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - node_modules_cache:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - GENERATE_SOURCEMAP=false
    stdin_open: true

volumes:
  bundle_cache:
  node_modules_cache:
